app_path: /usr/share/nginx/html
component: frontend
#secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/frontend token={{vault_token}} url=https://vault-internal.devrobo.online:8200 validate_certs=false')}}"
secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/frontend token={{vault_token}} url=http://vault-internal.devrobo.online:8200 ')}}"