component: user
app_path: /app

#secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/user token={{vault_token}} url=https://vault-internal.devrobo.online:8200 validate_certs=false')}}"
secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/user token={{vault_token}} url=http://vault-internal.devrobo.online:8200 ')}}"