component: mysql

# secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/mysql token={{vault_token}} url=https://vault-internal.devrobo.online:8200')}}"
secrets: "{{ lookup('hashi_vault', 'secret=roboshop-{{env}}/data/mysql token={{vault_token}} url=http://vault-internal.devrobo.online:8200')}}"